version: '3.8'

services:
  labelstudio:
    image: heartexlabs/label-studio:latest
    container_name: label-studio
    environment:
      LABEL_STUDIO_USERNAME: ${LABEL_STUDIO_ADMIN_USERNAME}
      LABEL_STUDIO_PASSWORD: ${LABEL_STUDIO_ADMIN_PASSWORD}
      LABEL_STUDIO_DISABLE_SIGNUP_WITHOUT_LINK: "true"
      LOCAL_FILES_SERVING_ENABLED: "true"
      LABEL_STUDIO_LOCAL_FILES_SERVING_ENABLED: "true"
      LABEL_STUDIO_LOCAL_FILES_DOCUMENT_ROOT: "/data"
    ports:
      - "0.0.0.0:${LABEL_STUDIO_PORT}:8080"
    volumes:
      - label_studio_data:/label-studio/data
      - ./data:/data
      - ./exports:/exports
    restart: unless-stopped
    networks:
      - labelstudio-network

volumes:
  label_studio_data:
    driver: local

networks:
  labelstudio-network:
    driver: bridge