version: '3.8'

services:
  labelstudio:
    image: heartexlabs/label-studio:latest
    container_name: label-studio
    environment:
      LABEL_STUDIO_USERNAME: ${LABEL_STUDIO_ADMIN_USERNAME}
      LABEL_STUDIO_PASSWORD: ${LABEL_STUDIO_ADMIN_PASSWORD}
      LABEL_STUDIO_DISABLE_SIGNUP_WITHOUT_LINK: "true"
      LOCAL_FILES_SERVING_ENABLED: "true"
      LABEL_STUDIO_LOCAL_FILES_SERVING_ENABLED: "true"
      LABEL_STUDIO_LOCAL_FILES_DOCUMENT_ROOT: "/data"
      PS1: 'label-studio # ' # Set prompt for interactive sessions
    ports:
      - "0.0.0.0:${LABEL_STUDIO_PORT}:8080"
    volumes:
      - label_studio_data:/label-studio/data
      - ./data:/data
      - ./exports:/exports
    restart: unless-stopped
    networks:
      - labelstudio-network

  backup:
    image: alpine:latest
    container_name: label-studio-backup
    environment:
      - TZ=America/Bogota # Establece la zona horaria a Colombia para que el cron se ejecute en hora local.
      - PS1='label-studio-backup # ' # Set prompt for interactive sessions
    volumes:
      - label_studio_data:/data
      - ./backups:/backups
      - ./scripts/backup.sh:/app/backup.sh
    restart: unless-stopped
    networks:
      - labelstudio-network
    entrypoint: sh -c "echo '0 6,14,22 * * * /app/backup.sh' | crontab - && crond -f"

volumes:
  label_studio_data:
    driver: local

networks:
  labelstudio-network:
    driver: bridge